title: Business Central on Azure DevOps
description: Everything about developing for Business Central on Azure DevOps
theme: jekyll-theme-cayman
imagesurl: https://BConDevOps.github.io/images
url: https://BConDevOps.github.io